// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtrpndFdWdFjeWpB-uq_8mZVDkuf8TIAY',
    appId: '1:695929597014:android:5d4cfd7a4f9aedd3665ff7',
    messagingSenderId: '695929597014',
    projectId: 'itax-login',
    databaseURL: 'https://itax-login-default-rtdb.firebaseio.com',
    storageBucket: 'itax-login.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBuXDJMqLYgTII8spG7jd5yKGul6uiZqBI",
      authDomain: "itax-login.firebaseapp.com",
      databaseURL: "https://itax-login-default-rtdb.firebaseio.com",
      projectId: "itax-login",
      storageBucket: "itax-login.firebasestorage.app",
      messagingSenderId: "695929597014",
      appId: "1:695929597014:web:0f7958f07356d30b665ff7",
      measurementId: "G-KEQEESZVYV"
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyBuXDJMqLYgTII8spG7jd5yKGul6uiZqBI",
      authDomain: "itax-login.firebaseapp.com",
      databaseURL: "https://itax-login-default-rtdb.firebaseio.com",
      projectId: "itax-login",
      storageBucket: "itax-login.firebasestorage.app",
      messagingSenderId: "695929597014",
      appId: "1:695929597014:web:0f7958f07356d30b665ff7",
      measurementId: "G-KEQEESZVYV"
  );

}